import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export const metadata = {
  title: 'Privacy Policy — TravelPanel',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      <div className="max-w-prose mx-auto px-6 py-12">
        {/* Back */}
        <Link href="/" className="inline-flex items-center gap-1.5 text-sm text-indigo-600 dark:text-indigo-400 mb-8 hover:underline">
          <ArrowLeft size={14} /> Back to TravelPanel
        </Link>

        <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">Privacy Policy</h1>
        <p className="text-sm text-gray-500 dark:text-gray-400 mb-8">Last updated: June 2026</p>

        <div className="prose dark:prose-invert prose-sm max-w-none space-y-6 text-gray-700 dark:text-gray-300">

          <section>
            <h2 className="text-base font-bold text-gray-900 dark:text-white mb-2">Your data lives on your device</h2>
            <p>
              TravelPanel stores all clips, boards, and plans in your device&apos;s local storage (IndexedDB). We do not run a database that contains your personal data. Your travel ideas are yours.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 dark:text-white mb-2">What we send to AI</h2>
            <p>
              When you save a clip, we send the URL (and optionally a screenshot or shared text) to Anthropic&apos;s Claude API. This is used solely to extract location names, activities, and travel wisdom from the content. We do not send your name, email, or any account information to Anthropic.
            </p>
            <p>
              Anthropic&apos;s data use is governed by their <a href="https://www.anthropic.com/privacy" className="text-indigo-600 dark:text-indigo-400 underline">Privacy Policy</a>.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 dark:text-white mb-2">Analytics</h2>
            <p>
              We use PostHog for anonymous product analytics (feature usage, clip counts, plan generation rates). PostHog receives: a random anonymous device ID, event names (e.g. &ldquo;clip_saved&rdquo;), and basic metadata (platform detected, number of locations found). No names, email addresses, or URLs are sent to PostHog.
            </p>
            <p>
              Analytics are only active when a PostHog API key is configured. You can opt out by disabling analytics in your device settings or blocking network requests to <code>app.posthog.com</code>.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 dark:text-white mb-2">What data is stored locally</h2>
            <ul className="list-disc pl-5 space-y-1">
              <li>URLs and titles of pages you clip</li>
              <li>AI-extracted location names, coordinates, activities, and substance (tips/warnings)</li>
              <li>Board names and organisation</li>
              <li>Trip plans generated by AI</li>
              <li>Personal notes you write on clips or in the timeline</li>
              <li>App settings (theme, onboarding completion)</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 dark:text-white mb-2">How to delete your data</h2>
            <p>
              Go to <strong>Settings → Export all my data</strong> if you want a backup first. Then clear your browser&apos;s site data for TravelPanel (or delete the app on iOS) to remove everything from your device. There is no server-side account to delete.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 dark:text-white mb-2">Contact</h2>
            <p>
              Questions? Email us at <a href="mailto:jiangnan027@gmail.com" className="text-indigo-600 dark:text-indigo-400 underline">jiangnan027@gmail.com</a>.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
