import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service — TravelPanel',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900">
      <div className="max-w-prose mx-auto px-6 py-12">
        {/* Back */}
        <Link href="/" className="inline-flex items-center gap-1.5 text-sm text-indigo-600 dark:text-indigo-400 mb-8 hover:underline">
          <ArrowLeft size={14} /> Back to TravelPanel
        </Link>

        <h1 className="text-2xl font-bold text-gray-900 dark:text-white mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-500 dark:text-gray-400 mb-8">Last updated: June 2026</p>

        <div className="prose dark:prose-invert prose-sm max-w-none space-y-6 text-gray-700 dark:text-gray-300">

          <section>
            <h2 className="text-base font-bold text-gray-900 dark:text-white mb-2">Use of TravelPanel</h2>
            <p>
              TravelPanel is a personal travel organisation tool. You may use it to save travel inspiration, organise clips into boards, and generate AI trip plans for personal, non-commercial purposes.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 dark:text-white mb-2">Usage limits</h2>
            <p>
              To manage AI costs, trip plan generation is rate-limited to 5 plans per day per device. This limit may change. Heavy usage that exceeds fair-use thresholds may result in temporary throttling.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 dark:text-white mb-2">AI-generated content</h2>
            <p>
              Trip plans, location descriptions, activity suggestions, and substance extractions are generated by Claude (Anthropic). They are provided for informational purposes only. TravelPanel does not guarantee the accuracy, safety, or timeliness of AI-generated content.
            </p>
            <p>
              <strong>Do not rely solely on AI-generated itineraries for safety-critical decisions</strong> such as mountaineering routes, entry requirements, or medical advice. Always verify independently before travelling.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 dark:text-white mb-2">No liability for travel plans</h2>
            <p>
              TravelPanel and its creators are not liable for any loss, injury, expense, or damage arising from use of the app or any AI-generated travel plan. Travel carries inherent risks; you are responsible for your own safety and compliance with local laws.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 dark:text-white mb-2">Third-party content</h2>
            <p>
              TravelPanel clips content from third-party platforms (Instagram, YouTube, Xiaohongshu, etc.) at your request. You are responsible for ensuring your use of those platforms complies with their own terms of service. TravelPanel does not store or redistribute third-party content beyond your local device.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 dark:text-white mb-2">Changes to these terms</h2>
            <p>
              We may update these terms at any time. Continued use of TravelPanel after changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 dark:text-white mb-2">Contact</h2>
            <p>
              Questions? Email us at <a href="mailto:jiangnan027@gmail.com" className="text-indigo-600 dark:text-indigo-400 underline">jiangnan027@gmail.com</a>.
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
