import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export const metadata = {
  title: 'Terms of Service — TravelPanel',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white">
      <div className="max-w-2xl mx-auto px-6 py-12">
        {/* Back */}
        <Link
          href="/settings"
          className="inline-flex items-center gap-2 text-indigo-600 text-sm font-medium hover:underline mb-8"
        >
          <ArrowLeft size={14} />
          Back to Settings
        </Link>

        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Service</h1>
        <p className="text-sm text-gray-400 mb-10">Effective date: June 10, 2026</p>

        <div className="space-y-8 text-gray-700 leading-relaxed">

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">Acceptance</h2>
            <p>
              By using TravelPanel, you agree to these Terms of Service. If you do not agree,
              please do not use the app.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">Permitted use</h2>
            <p>TravelPanel is provided for personal, non-commercial travel planning use. You may not:</p>
            <ul className="mt-3 space-y-1.5 pl-5 list-disc text-sm">
              <li>Use the app to infringe any intellectual property rights</li>
              <li>Attempt to circumvent rate limits or access controls</li>
              <li>Use the AI extraction features to scrape content at scale</li>
              <li>Resell or redistribute the app or its output without permission</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">Content you save</h2>
            <p>
              You are responsible for ensuring you have the right to save and process links and
              content you submit to TravelPanel. We do not claim ownership of your clips, boards,
              or trip plans.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">AI-generated content</h2>
            <p>
              Trip plans and extracted content are generated by AI and may be inaccurate, incomplete,
              or outdated. Always verify travel information independently, especially regarding
              opening hours, prices, safety conditions, and entry requirements.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">No warranty</h2>
            <p>
              TravelPanel is provided "as is" without warranty of any kind. We make no guarantees
              about uptime, accuracy, or fitness for any particular purpose. Use the app at your
              own risk.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">Limitation of liability</h2>
            <p>
              To the fullest extent permitted by law, TravelPanel and its creators are not liable
              for any indirect, incidental, special, or consequential damages arising from your use
              of the app, including lost data, travel disruptions, or financial losses based on
              AI-generated itineraries.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">Service availability</h2>
            <p>
              We reserve the right to modify, suspend, or discontinue the service at any time
              without notice. We will not be liable for any such action.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">Governing law</h2>
            <p>
              These terms are governed by the laws of the jurisdiction in which the service operator
              is located, without regard to conflict-of-law principles.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-bold text-gray-900 mb-3">Contact</h2>
            <p>
              Questions about these terms? Email{' '}
              <a href="mailto:jiangnan027@gmail.com" className="text-indigo-600 hover:underline">
                jiangnan027@gmail.com
              </a>.
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-gray-100 flex gap-6 text-sm text-gray-400">
          <Link href="/privacy" className="hover:text-indigo-600 transition-colors">Privacy Policy</Link>
          <Link href="/terms" className="hover:text-indigo-600 transition-colors font-medium text-gray-700">Terms of Service</Link>
          <Link href="/settings" className="hover:text-indigo-600 transition-colors">Settings</Link>
        </div>
      </div>
    </div>
  );
}
