import Link from 'next/link';
import { ArrowLeft } from 'lucide-react';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-white dark:bg-gray-900 px-5 pt-status pb-16">
      <div className="max-w-prose mx-auto">
        {/* Back */}
        <div className="pt-6 pb-4">
          <Link
            href="/settings"
            className="inline-flex items-center gap-1.5 text-indigo-600 dark:text-indigo-400 text-sm font-medium"
          >
            <ArrowLeft size={15} />
            Settings
          </Link>
        </div>

        <h1 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-1">Terms of Use</h1>
        <p className="text-xs text-gray-400 dark:text-gray-500 mb-8">Last updated: June 2026</p>

        <div className="space-y-6 text-sm text-gray-700 dark:text-gray-300 leading-relaxed">

          <section>
            <h2 className="font-semibold text-gray-900 dark:text-gray-100 text-base mb-2">Acceptance</h2>
            <p>
              By using TravelPanel you agree to these terms. If you do not agree, please stop using the app.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-gray-900 dark:text-gray-100 text-base mb-2">License</h2>
            <p>
              We grant you a personal, non-transferable, non-exclusive license to use TravelPanel for your
              private, non-commercial travel planning. You may not redistribute, copy, or reverse-engineer
              the app.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-gray-900 dark:text-gray-100 text-base mb-2">Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 mt-1 space-y-1">
              <li>Use the app to scrape or aggregate third-party content at scale</li>
              <li>Circumvent rate limits or abuse the AI extraction feature</li>
              <li>Use the app for any unlawful purpose</li>
            </ul>
          </section>

          <section>
            <h2 className="font-semibold text-gray-900 dark:text-gray-100 text-base mb-2">AI-generated content</h2>
            <p>
              Trip plans and location extractions are generated by AI (Anthropic Claude) and may contain
              inaccuracies. Always verify travel information with official sources before booking.
              TravelPanel is not responsible for decisions made based on AI-generated content.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-gray-900 dark:text-gray-100 text-base mb-2">Disclaimer</h2>
            <p>
              The app is provided &ldquo;as is&rdquo; without warranty of any kind. We are not liable for
              any loss of data, inaccurate travel suggestions, or third-party service disruptions.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-gray-900 dark:text-gray-100 text-base mb-2">Changes</h2>
            <p>
              We may update these terms at any time. Continued use of the app after changes constitutes
              acceptance of the updated terms.
            </p>
          </section>

          <section>
            <h2 className="font-semibold text-gray-900 dark:text-gray-100 text-base mb-2">Contact</h2>
            <p>
              Questions?{' '}
              <a
                href="mailto:jiangnan027@gmail.com"
                className="text-indigo-600 dark:text-indigo-400 underline"
              >
                jiangnan027@gmail.com
              </a>
            </p>
          </section>

        </div>
      </div>
    </div>
  );
}
