'use client';

import { useRouter } from 'next/navigation';
import { ArrowLeft } from 'lucide-react';

export default function TermsOfServicePage() {
  const router = useRouter();

  return (
    <div className="min-h-screen bg-white">
      {/* Header */}
      <div className="bg-white border-b border-gray-100 px-4 pt-12 pb-4 sticky top-0 z-10">
        <div className="flex items-center gap-3">
          <button
            onClick={() => router.back()}
            className="p-2 text-gray-500 hover:text-gray-700 hover:bg-gray-100 rounded-xl -ml-1"
          >
            <ArrowLeft size={20} />
          </button>
          <h1 className="text-lg font-bold text-gray-900">Terms of Service</h1>
        </div>
        <p className="text-xs text-gray-400 mt-1 ml-11">Last updated: June 2026</p>
      </div>

      <div className="px-5 py-6 max-w-2xl mx-auto">

        <section className="mb-6">
          <h2 className="text-base font-semibold text-gray-800 mb-2">Welcome to TravelPanel</h2>
          <p className="text-sm text-gray-600 leading-relaxed">
            By using TravelPanel you agree to these terms. If you don't agree, please don't use the app. These are written plainly — no tricks.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-base font-semibold text-gray-800 mb-2">What TravelPanel does</h2>
          <p className="text-sm text-gray-600 leading-relaxed">
            TravelPanel helps you save travel inspiration from the web, extract locations and tips using AI, and plan trips. All your data is stored locally on your device unless you choose to export it.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-base font-semibold text-gray-800 mb-2">Your content</h2>
          <p className="text-sm text-gray-600 leading-relaxed mb-3">
            You own your clips, notes, and trip plans. We don't claim any rights to your content. When you use the AI extraction feature, the URL and page text are sent to Anthropic's API — you're responsible for only clipping content you have the right to access.
          </p>
          <p className="text-sm text-gray-600 leading-relaxed">
            Please don't use TravelPanel to clip or reproduce content in ways that violate copyright or the terms of service of the source platform.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-base font-semibold text-gray-800 mb-2">Acceptable use</h2>
          <p className="text-sm text-gray-600 leading-relaxed mb-2">Don't use TravelPanel to:</p>
          <ul className="text-sm text-gray-600 space-y-1.5 list-disc pl-4">
            <li>Scrape or bulk-extract content from third-party platforms</li>
            <li>Circumvent the terms of service of Instagram, YouTube, or other platforms</li>
            <li>Attempt to reverse-engineer or misuse the API endpoints</li>
            <li>Use the app for any unlawful purpose</li>
          </ul>
        </section>

        <section className="mb-6">
          <h2 className="text-base font-semibold text-gray-800 mb-2">AI-generated content</h2>
          <p className="text-sm text-gray-600 leading-relaxed">
            Trip plans and location extractions are generated by AI and may contain errors. Always verify important information (opening hours, prices, safety conditions) from authoritative sources before travelling. TravelPanel is an inspiration tool, not a navigation or booking service.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-base font-semibold text-gray-800 mb-2">Service availability</h2>
          <p className="text-sm text-gray-600 leading-relaxed">
            TravelPanel is provided "as is." We aim for high availability but can't guarantee the AI extraction service will always be online. Your locally stored data is always accessible offline, regardless of service status.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-base font-semibold text-gray-800 mb-2">Liability</h2>
          <p className="text-sm text-gray-600 leading-relaxed">
            To the extent permitted by law, TravelPanel is not liable for any loss or damage arising from your use of the app, reliance on AI-generated content, or data loss due to device issues. Your data is local — back it up regularly using the export feature.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-base font-semibold text-gray-800 mb-2">Changes to these terms</h2>
          <p className="text-sm text-gray-600 leading-relaxed">
            We may update these terms occasionally. Continued use of TravelPanel after changes means you accept the updated terms. We'll update the "last updated" date above when we do.
          </p>
        </section>

        <section className="mb-6">
          <h2 className="text-base font-semibold text-gray-800 mb-2">Contact</h2>
          <p className="text-sm text-gray-600 leading-relaxed">
            Questions about these terms? Email us at{' '}
            <a href="mailto:jiangnan027@gmail.com" className="text-indigo-600 hover:underline">
              jiangnan027@gmail.com
            </a>
          </p>
        </section>

      </div>
    </div>
  );
}
